### ISSUE TITLE
Avoid Recalculation of style

### ISSUE THREAD

**Issue by NiciusB** [lindsayevans/outline.js#3]
Right now, every mouse click or keyboard press is changing the content of the style tag, forcing the browser to recalculate the style:
![image](https://user-images.githubusercontent.com/2421121/45953237-bf359a80-c009-11e8-8a32-4aefea54c7c3.png)

You can avoid changing the content of style_element on set_css if the new content is the same as the current one.
Since I don't need support for IE, I have used the following:
```
set_css = function(css_text){
    if (css_text !== style_element.innerHTML) style_element.innerHTML = css_text;
}
```

However, the code can be changed to allow support for IE by checking the other method as well, or maybe keeping a boolean variable inside the anonymous function

**Comment by lindsayevans** [comment]
Thanks @NiciusB - I'll look at fixing this in v2
